name: Integration Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    # Install minimap2 using conda
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: '3.9'
        channels: bioconda,conda-forge,defaults
    
    - name: Install minimap2
      shell: bash -l {0}  # Important: use login shell for conda
      run: |
        conda install -c bioconda minimap2 -y
        which minimap2  # Verify installation
        minimap2 --version  # Test it works

    - name: Install subread for featureCounts
      shell: bash -l {0}  # Important: use login shell for conda
      run: |
        conda install -c bioconda subread -y
        which subread  # Verify installation
        subread --version  # Test it works
    
    - name: Install Python dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install pandas
        pip install biopython
        pip install random2
    
    - name: Run tests
      shell: bash -l {0}  # Use conda environment
      run: pytest -v
    
    - name: Clean up __pycache__ directories
      if: always()
      run: |
        echo "Cleaning up __pycache__ directories..."
        find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
        find . -name "*.pyc" -delete 2>/dev/null || true
        find . -name "*.pyo" -delete 2>/dev/null || true
        echo "Cleanup complete"
    
    - name: Clean up test artifacts
      if: always()
      run: |
        echo "Cleaning up test artifacts..."
        find . -name "*.paf" -delete 2>/dev/null || true
        find . -name "*_assembly*.fasta" -delete 2>/dev/null || true
        find . -name "*_bin*.fasta" -delete 2>/dev/null || true
        echo "Test artifacts cleanup complete"
