name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    
    - name: Run tests
      run: pytest test_integration.py -v

# Cleanup
   - name: Clean up __pycache__ directories
      if: always()
      run: |
        echo "Cleaning up __pycache__ directories..."
        find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
        find . -name "*.pyc" -delete 2>/dev/null || true
        find . -name "*.pyo" -delete 2>/dev/null || true
        echo "✅ __pycache__ cleanup complete"
    
    - name: Clean up test artifacts
      if: always()
      run: |
        echo "Cleaning up test artifacts..."
        find . -name "*.paf" -delete 2>/dev/null || true
        find . -name "*_assembly*.fasta" -delete 2>/dev/null || true
        find . -name "*_bin*.fasta" -delete 2>/dev/null || true
        echo "✅ Test artifacts cleanup complete"
